### ISSUE TITLE
bluetoothd SIGSEGV on bluez 5.56

### ISSUE THREAD

**Issue by pv** [bluez/bluez#115]
Got a segfault in bluez 5.56 (Fedora `bluez-5.56-1.fc33.x86_64`), when using together with pipewire. Bluetoothd seems to sometimes crash when SetConfiguration etc. transport events are done. This happens uncommonly maybe once a week and I don't have a reliable reproducer, but they appear in logs now and then.

Backtrace:
```
(gdb) thr a a bt

Thread 1 (Thread 0x7f97b8275380 (LWP 993)):
#0  0x00007f97b87b0afe in __strcmp_avx2 () from /lib64/libc.so.6
#1  0x00005633cb8fcf71 in match_endpoint_by_path (a=<optimized out>, b=<optimized out>) at profiles/audio/media.c:2188
#2  0x00005633cb97a504 in queue_remove_if (queue=0x5633cc8865f0, function=0x5633cb8fcf60 <match_endpoint_by_path>, user_data=0x5633cc8d68e0) at src/shared/queue.c:279
#3  0x00005633cb902f40 in proxy_removed_cb (proxy=<optimized out>, user_data=0x5633cc8a0a40) at profiles/audio/media.c:2210
#4  0x00005633cb978ffd in proxy_free (data=0x5633cc873940) at gdbus/client.c:568
#5  0x00007f97b88b9e40 in g_list_foreach () from /lib64/libglib-2.0.so.0
#6  0x00007f97b88c488f in g_list_free_full () from /lib64/libglib-2.0.so.0
#7  0x00005633cb973cca in service_disconnect (conn=0x5633cc86d470, user_data=0x5633cc8bed50) at gdbus/client.c:1300
#8  0x00005633cb9764f8 in service_filter (connection=0x5633cc86d470, message=<optimized out>, user_data=0x5633cc885c00) at gdbus/watch.c:471
#9  0x00005633cb975983 in message_filter (connection=0x5633cc86d470, message=0x5633cc8810c0, user_data=<optimized out>) at gdbus/watch.c:544
#10 0x00007f97b883e221 in dbus_connection_dispatch () from /lib64/libdbus-1.so.3
#11 0x00005633cb971958 in message_dispatch (data=0x5633cc86d470) at gdbus/mainloop.c:59
#12 0x00007f97b88c8b5b in g_idle_dispatch () from /lib64/libglib-2.0.so.0
#13 0x00007f97b88c9a9f in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#14 0x00007f97b891ba98 in g_main_context_iterate.constprop () from /lib64/libglib-2.0.so.0
#15 0x00007f97b88c9163 in g_main_loop_run () from /lib64/libglib-2.0.so.0
#16 0x00005633cb8ed1a9 in mainloop_run () at src/shared/mainloop-glib.c:66
#17 mainloop_run_with_signal (func=0x5633cb92ec20 <signal_callback>, user_data=0x0) at src/shared/mainloop-notify.c:188
#18 main (argc=<optimized out>, argv=<optimized out>) at src/main.c:1084
(gdb) up
#1  0x00005633cb8fcf71 in match_endpoint_by_path (a=<optimized out>, b=<optimized out>)
    at profiles/audio/media.c:2188
2188		return !strcmp(endpoint->path, path);
(gdb) up
#2  0x00005633cb97a504 in queue_remove_if (queue=0x5633cc8865f0, 
    function=0x5633cb8fcf60 <match_endpoint_by_path>, user_data=0x5633cc8d68e0)
    at src/shared/queue.c:279
279			if (function(entry->data, user_data)) {
(gdb) p function
$4 = (queue_match_func_t) 0x5633cb8fcf60 <match_endpoint_by_path>
(gdb) p *(struct media_endpoint *)entry->data   # garbage?
$1 = {sep = 0x5636afb57d0d, sender = 0x5633cc8b0c00 "UTF-8", 
  path = 0x20 <error: Cannot access memory at address 0x20>, 
  uuid = 0x31 <error: Cannot access memory at address 0x31>, codec = 112 'p', 
  capabilities = 0x0, size = 94780474955264, hs_watch = 0, ag_watch = 0, watch = 0, 
  requests = 0x21 = {<error reading variable>
(gdb) p (char *)user_data
$2 = 0x5633cc8d68e0 "/MediaEndpoint/A2DPSource/ldac"
```

Haven't been running bluez master, so I don't know if it's already fixed.

**Comment by pv** [comment]
Oops, duplicate of #109
