### ISSUE TITLE
 bluetoothd crashes when discover_devices is terminated

### ISSUE THREAD

**Issue by AndreRH** [bluez/bluez#196]
When using discover_devices from bluer on ARMv7, bluetoothd exits with signal 6/ABRT:
free(): invalid next size (fast)
or
realloc(): invalid next size

tested with 5.55, 5.60 and 5.61

see also https://github.com/bluez/bluer/issues/9

**Comment by AndreRH** [comment]
==3710== Invalid write of size 4
==3710==    at 0x495F9E8: ??? (in /usr/lib/libdbus-1.so.3.19.11)
==3710==  Address 0x4c7ac79 is 17 bytes inside a block of size 20 alloc'd
==3710==    at 0x48409A0: malloc (in /usr/lib/valgrind/vgpreload_memcheck-arm-linux.so)
==3710== 

This happens when I start discover_devices, note that this doesn't happen with "scan on" in bluetoothctl, "hcitool scan" or with "hcitool lescan"

I'll try to get some debugsymbols, but it's not that easy for this particular system... So maybe someone could guess what's going on from the allocation size?

**Comment by AndreRH** [comment]
Ok, with debug symbols:

==678== Invalid write of size 4
==678==    at 0x496B252: _dbus_marshal_read_basic (in /usr/lib/libdbus-1.so.3.19.11)
==678==  Address 0x4c78529 is 17 bytes inside a block of size 20 alloc'd
==678==    at 0x48409A0: malloc (in /usr/lib/valgrind/vgpreload_memcheck-arm-linux.so)
==678==

**Comment by Vudentz** [comment]
Ouch, it seems to be crashing libdbus parsing.

**Comment by AndreRH** [comment]
It took me some time, but here we have a better backtrace:
==850== Invalid write of size 4
==850==    at 0x49616D0: _dbus_marshal_read_basic (dbus-marshal-basic.c:540)
==850==    by 0x495445D: _dbus_type_reader_read_basic (dbus-marshal-recursive.c:879)
==850==    by 0x49572F3: dbus_message_iter_get_basic (dbus-message.c:2359)
==850==    by 0x4E7F9: parse_discoverable (adapter.c:2465)
==850==    by 0x4E943: parse_discovery_filter_entry (adapter.c:2507)
==850==    by 0x5071B: parse_discovery_filter_dict (adapter.c:2565)
==850==    by 0x56D17: set_discovery_filter (adapter.c:2616)
==850==    by 0x78685: process_message (object.c:246)
==850==    by 0x78927: generic_message (object.c:1066)
==850==    by 0x495A6BD: _dbus_object_tree_dispatch_and_unlock (dbus-object-tree.c:1020)
==850==    by 0x4950DC7: dbus_connection_dispatch (dbus-connection.c:4745)
==850==    by 0x7683D: message_dispatch (mainloop.c:59)
==850==  Address 0x4c70529 is 17 bytes inside a block of size 20 alloc'd
==850==    at 0x483F9A0: malloc (in /usr/lib/valgrind/vgpreload_memcheck-arm-linux.so)
==850==

**Comment by AndreRH** [comment]
And gdb says:
Program received signal SIGABRT, Aborted.
__libc_do_syscall () at libc-do-syscall.S:49
49	libc-do-syscall.S: No such file or directory.
(gdb) bt
#0  __libc_do_syscall () at libc-do-syscall.S:49
#1  0xb6dd85c6 in __libc_signal_restore_set (set=0xbefff558) at ../sysdeps/unix/sysv/linux/internal-signals.h:86
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb6dd9146 in __GI_abort () at abort.c:79
#4  0xb6e001c4 in __libc_message (action=action@entry=do_abort, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:155
#5  0xb6e0560a in malloc_printerr (str=<optimized out>) at malloc.c:5347
#6  0xb6e056c4 in unlink_chunk (av=av@entry=0xb6e9c59c <main_arena>, p=p@entry=0xf5a40) at malloc.c:1454
#7  0xb6e078ac in _int_realloc (av=av@entry=0xb6e9c59c <main_arena>, oldp=oldp@entry=0xf5a28, oldsize=oldsize@entry=24, nb=nb@entry=40) at malloc.c:4594
#8  0xb6e089a4 in __GI___libc_realloc (oldmem=0xf5a30, bytes=32) at malloc.c:3226
#9  0xb6ed483a in dbus_realloc (memory=<optimized out>, bytes=bytes@entry=32) at ../../dbus-1.12.16/dbus/dbus-memory.c:679
#10 0xb6ed4b5c in reallocate_for_length (real=real@entry=0xbefff8f4, new_length=new_length@entry=14) at ../../dbus-1.12.16/dbus/dbus-string.c:366
#11 0xb6ed4bbe in set_length (real=real@entry=0xbefff8f4, new_length=14) at ../../dbus-1.12.16/dbus/dbus-string.c:407
#12 0xb6ed4bf4 in open_gap (len=len@entry=9, dest=dest@entry=0xbefff8f4, insert_at=insert_at@entry=5) at ../../dbus-1.12.16/dbus/dbus-string.c:428
#13 0xb6ed4c2c in copy (source=source@entry=0xbefff834, start=start@entry=0, len=len@entry=9, dest=dest@entry=0xbefff8f4, insert_at=insert_at@entry=5) at ../../dbus-1.12.16/dbus/dbus-string.c:1216
#14 0xb6ed50bc in _dbus_string_copy_len (source=source@entry=0xbefff834, start=start@entry=0, len=len@entry=9, dest=dest@entry=0xbefff8f4, insert_at=5) at ../../dbus-1.12.16/dbus/dbus-string.c:1386
#15 0xb6ed4042 in marshal_len_followed_by_bytes (marshal_as=marshal_as@entry=1, str=str@entry=0xbefff8f4, insert_at=insert_at@entry=4, value=value@entry=0xf62e8 "sa{sv}as", data_len=8, 
    byte_order=byte_order@entry=108, pos_after=pos_after@entry=0xbefff8e4) at ../../dbus-1.12.16/dbus/dbus-marshal-basic.c:730
#16 0xb6ed40e8 in marshal_signature (str=0xbefff8f4, insert_at=4, value=0xf62e8 "sa{sv}as", pos_after=pos_after@entry=0xbefff8e4) at ../../dbus-1.12.16/dbus/dbus-marshal-basic.c:774
#17 0xb6ed4322 in _dbus_marshal_write_basic (str=<optimized out>, insert_at=4, type=type@entry=103, value=value@entry=0xbefff9ec, byte_order=108, pos_after=pos_after@entry=0xbefff8e4)
    at ../../dbus-1.12.16/dbus/dbus-marshal-basic.c:848
#18 0xb6ec713c in _dbus_type_writer_write_basic_no_typecode (writer=writer@entry=0xbefff8d4, type=type@entry=103, value=value@entry=0xbefff9ec) at ../../dbus-1.12.16/dbus/dbus-marshal-recursive.c:1605
#19 0xb6ec79f8 in _dbus_type_writer_write_basic (writer=writer@entry=0xbefff8d4, type=type@entry=103, value=value@entry=0xbefff9ec) at ../../dbus-1.12.16/dbus/dbus-marshal-recursive.c:2327
#20 0xb6ec7d7c in reader_set_basic_variable_length (reader=reader@entry=0xbefff938, current_type=current_type@entry=103, value=value@entry=0xbefff9ec, realign_root=realign_root@entry=0xbefff9a8)
    at ../../dbus-1.12.16/dbus/dbus-marshal-recursive.c:1301
#21 0xb6ec7dca in _dbus_type_reader_set_basic (reader=reader@entry=0xbefff938, value=value@entry=0xbefff9ec, realign_root=realign_root@entry=0xbefff9a8) at ../../dbus-1.12.16/dbus/dbus-marshal-recursive.c:1398
#22 0xb6ec61b0 in set_basic_field (reader=reader@entry=0xbefff988, field=field@entry=8, type=type@entry=103, value=value@entry=0xbefff9ec, realign_root=realign_root@entry=0xbefff9a8)
    at ../../dbus-1.12.16/dbus/dbus-marshal-header.c:373
#23 0xb6ec6662 in _dbus_header_set_field_basic (header=0xd5e64, field=field@entry=8, type=type@entry=103, value=value@entry=0xbefff9ec) at ../../dbus-1.12.16/dbus/dbus-marshal-header.c:1293
#24 0xb6ec9386 in _dbus_message_iter_close_signature (real=real@entry=0xbefffa88) at ../../dbus-1.12.16/dbus/dbus-message.c:2619
#25 0xb6ecac44 in dbus_message_iter_close_container (iter=iter@entry=0xbefffa88, sub=sub@entry=0xbefffa18) at ../../dbus-1.12.16/dbus/dbus-message.c:3066
#26 0x00077b1a in process_properties_from_interface (data=data@entry=0xf2610, iface=0xf2758) at ../bluez-5.61/gdbus/object.c:1712
#27 0x00077b60 in process_property_changes (data=data@entry=0xf2610) at ../bluez-5.61/gdbus/object.c:1731
#28 0x00077c3e in process_changes (user_data=0xf2610, user_data@entry=<error reading variable: value has been optimized out>) at ../bluez-5.61/gdbus/object.c:1000
#29 0xb6f29ef4 in g_idle_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../glib-2.62.6/glib/gmain.c:5654
#30 0xb6f2a78e in g_main_dispatch (context=context@entry=0xd0ea8) at ../glib-2.62.6/glib/gmain.c:3216
#31 0xb6f2c7b0 in g_main_context_dispatch (context=context@entry=0xd0ea8) at ../glib-2.62.6/glib/gmain.c:3881
#32 0xb6f2c896 in g_main_context_iterate (context=0xd0ea8, block=block@entry=1, dispatch=dispatch@entry=1, self=self@entry=0xf1000) at ../glib-2.62.6/glib/gmain.c:3954
#33 0xb6f2cbc0 in g_main_loop_run (loop=0xd2438) at ../glib-2.62.6/glib/gmain.c:4148
#34 0x000848da in mainloop_run () at ../bluez-5.61/src/shared/mainloop-glib.c:66
#35 0x00084b78 in mainloop_run_with_signal (func=func@entry=0x3cee5 <signal_callback>, user_data=user_data@entry=0x0) at ../bluez-5.61/src/shared/mainloop-notify.c:188
#36 0x0003e568 in main (argc=<optimized out>, argv=<optimized out>) at ../bluez-5.61/src/main.c:1121

**Comment by Vudentz** [comment]
@AndreRH We should probably inform libdbus folks since apparently there is something off with the message, perhaps it is truncated or something, which leads to this crash.

**Comment by ngoquang2708** [comment]
One more data point: it crashed on Raspi 3 (armv7), but not on Raspi 0 (armv6).

**Comment by FreshLuoBoGan** [comment]
![image](https://user-images.githubusercontent.com/28969782/190388627-2f344e3c-97d9-41df-9bdd-1cb0c49f7ef8.png)

**Comment by FreshLuoBoGan** [comment]
i have a similar issue，can i do something to resolved   it? @AndreRH 
![image](https://user-images.githubusercontent.com/28969782/190389024-edd5ad39-8cc9-469f-b56a-92181eb3ab97.png)

**Comment by Mille2525** [comment]
Hey everyone, I think I found the cause of this issue. See this comment for more info: https://github.com/bluez/bluer/issues/48#issuecomment-1809651435
