### ISSUE TITLE
Bluez version 5.62 - Spontaneous restart of the bluetooth daemon after previous successful connection

### ISSUE THREAD

**Issue by 0xa000** [bluez/bluez#219]
* Python version: 3.9.7
* Operating System: Arch Linux
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.62

### Description

I have a script that communicates with a Vernier "GoDirect" sensor using their "godirect" Python package. This package uses BlueZ (via Bleak) under the hood to handle the actual BLE communication. The script uses the godirect package to find the Vernier sensor, connect to it, and read data from it via GATT.

The script worked fine until I updated to BlueZ version 5.62. With this version of Bluez, every _second_ time I run the script, an exception is raised in BleakScannerBlueZDBus::start(), see the trace below.

I initially reported this issue to the Bleak issue tracker, since the problem manifests itself as an exception coming from Bleak. However, this exception seems to be the result of losing the DBus connection to the bluetooth daemon, which spontaneously restarts. See here for reference: https://github.com/hbldh/bleak/issues/674.
 
```
Traceback (most recent call last):
  File "godirect_ble_thread.py", line 66, in _acquisition_thread_main
    device = gd.get_device()
  File "/usr//lib/python3.9/site-packages/godirect/__init__.py", line 93, in get_device
    return self._ble_backend.scan_auto(threshold)
  File "/usr//lib/python3.9/site-packages/godirect/backend_bleak.py", line 49, in scan_auto
    devices = self.scan()
  File "/usr//lib/python3.9/site-packages/godirect/backend_bleak.py", line 38, in scan
    devices = loop.run_until_complete(self._async_scan())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/godirect/backend_bleak.py", line 21, in _async_scan
    bleak_devices = await discover()
  File "/usr/lib/python3.9/site-packages/bleak/backends/scanner.py", line 99, in discover
    async with cls(**kwargs) as scanner:
  File "/usr/lib/python3.9/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/scanner.py", line 123, in start
    assert_reply(reply)
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.NoReply] Message recipient disconnected from message bus without replying
```

The relevant code from Bleak (scanner.py, lines 114 - 123) is this:
```
# Find the HCI device to use for scanning and get cached device properties
reply = await self._bus.call(
    Message(
        destination=defs.BLUEZ_SERVICE,
        path="/",
        member="GetManagedObjects",
        interface=defs.OBJECT_MANAGER_INTERFACE,
    )
)
assert_reply(reply)
```
Here, `defs.BLUEZ_SERVICE` equals `"org.bluez"` and `defs.OBJECT_MANAGER_INTERFACE` equals `"org.freedesktop.DBus.ObjectManager"`.

The exception is raised by `assert_reply()` when it detects that the reply is of type `ERROR`.

This only happens if the sensor is switched on. If I switch the sensor off, then I can re-run as many times as I like and scanning works fine. However, if the sensor is switched on, is found during scanning, connected to, and used, then the next time I re-run the script, it will fail with the above exception.

### What I Did

I downgraded BlueZ to version 5.61 and with that version the problem described above does not occur.

With BlueZ version 5.62, I see in the system journal that the bluetooth daemon exits and restarts every time the problem occurs. It seems to exit cleanly, in the sense that no error is reported in the system journal. See the excerpt below.

```
Oct 21 16:16:52 hydra bluetoothd[2517]: Disconnected from D-Bus. Exiting.
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_453
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_453
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_512
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_512
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_552
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_552
Oct 21 16:16:52 hydra bluetoothd[2517]: Stopping SDP server
Oct 21 16:16:52 hydra bluetoothd[2517]: Exit
Oct 21 16:16:52 hydra systemd[1]: bluetooth.service: Deactivated successfully.
Oct 21 16:16:52 hydra audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 21 16:16:52 hydra kernel: audit: type=1131 audit(1634825812.484:232): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 21 16:16:59 hydra dbus-daemon[422]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.138' (uid=1000 pid=2533 comm="python godirect_ble_thread.py ")
Oct 21 16:16:59 hydra systemd[1]: Starting Bluetooth service...
Oct 21 16:16:59 hydra bluetoothd[2540]: Bluetooth daemon 5.62
Oct 21 16:16:59 hydra dbus-daemon[422]: [system] Successfully activated service 'org.bluez'
Oct 21 16:16:59 hydra systemd[1]: Started Bluetooth service.
Oct 21 16:16:59 hydra audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 21 16:16:59 hydra bluetoothd[2540]: Starting SDP server
Oct 21 16:16:59 hydra kernel: audit: type=1130 audit(1634825819.777:233): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 21 16:16:59 hydra bluetoothd[2540]: Bluetooth management interface 1.21 initialized
Oct 21 16:16:59 hydra bluetoothd[2540]: Failed to set privacy: Rejected (0x0b)
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_453
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_453
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_512
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_512
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_552
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_552
```

The fact that the bluetooth daemon exits (or crashes?) and restarts would explain the exception that the "recipient disconnected from the message bus without replying". But I do not understand how scanning after a successful connection would cause the bluetooth daemon to exit.

**Comment by hannes-ma** [comment]
We are experiencing the same problem on an embedded system (YOCTO-based linux 4.14.78, armv7 i.MX7). In our case the bluetooth daemon reports "Disconnected from D-Bus. Exiting." and exits after it disconnects from a timed out connection. This is reproducible.

```
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:dev_disconnected() Device 38:78:62:DB:91:2A disconnected, reason 1
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_remove_connection()
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/plugins/policy.c:disconnect_cb() reason 1
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:bonding_attempt_complete() hci0 bdaddr 38:78:62:DB:91:2A type 1 status 0xe
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:device_bonding_complete() bonding (nil) status 0x0e
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:device_bonding_failed() status 14
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:resume_discovery()
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:gatt_debug() Channel 0x12b5658 disconnected: Connection timed out
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:att_disconnected_cb()
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:att_disconnected_cb() Connection timed out (110)
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/service.c:change_state() 0x12bfea8: device 38:78:62:DB:91:2A profile gap-profile state changed: connected -> disconnecting (0)
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/service.c:change_state() 0x12bfea8: device 38:78:62:DB:91:2A profile gap-profile state changed: disconnecting -> disconnected (0)
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:btd_gatt_client_disconnected() Device disconnected. Cleaning up.
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:att_disconnected_cb() Automatic connection disabled
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-database.c:btd_gatt_database_att_disconnected()
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-database.c:att_disconnected()
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/attrib/gattrib.c:g_attrib_unref() 0x12c91d8: g_attrib_unref=0
Nov 12 11:04:44 daemon.info bluetoothd[954]: Disconnected from D-Bus. Exiting.
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/plugin.c:plugin_cleanup() Cleanup plugins
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/input/suspend-none.c:suspend_exit()
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/audio/a2dp.c:media_server_remove() path /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/plugins/hostname.c:hostname_remove()
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:btd_profile_cleanup() Releasing "Message Notification"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:ext_adapter_remove() "Message Notification" removed
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10005
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:remove_ext() Removed "Message Notification"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:btd_profile_cleanup() Releasing "Message Access"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:ext_adapter_remove() "Message Access" removed
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10006
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:remove_ext() Removed "Message Access"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:btd_profile_cleanup() Releasing "Phone Book Access"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:ext_adapter_remove() "Phone Book Access" removed
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10007
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:remove_ext() Removed "Phone Book Access"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:btd_profile_cleanup() Releasing "Synchronization"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:ext_adapter_remove() "Synchronization" removed
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10008
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:remove_ext() Removed "Synchronization"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:btd_profile_cleanup() Releasing "File Transfer"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:ext_adapter_remove() "File Transfer" removed
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10009
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:remove_ext() Removed "File Transfer"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:btd_profile_cleanup() Releasing "Object Push"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:ext_adapter_remove() "Object Push" removed
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x1000a
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/profile.c:remove_ext() Removed "Object Push"
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/agent.c:agent_destroy() agent :1.17
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/agent.c:agent_release() Releasing agent :1.17, /agent
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/agent.c:remove_default_agent() Default agent cleared
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:set_mode() sending set mode command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/agent.c:agent_unref() 0x12baad0: ref=0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_remove() Removing adapter /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:device_remove() Removing device /org/bluez/hci0/dev_CE_5C_12_9B_37_CE
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/service.c:change_state() 0x12bda98: device CE:5C:12:9B:37:CE profile gap-profile state changed: disconnected -> unavailable (0)
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/gap/gas.c:gap_remove() GAP profile remove (CE:5C:12:9B:37:CE)
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/service.c:btd_service_unref() 0x12bda98: ref=0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:btd_device_unref() Freeing device /org/bluez/hci0/dev_CE_5C_12_9B_37_CE
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:device_free() 0x12bee90
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:device_remove() Removing device /org/bluez/hci0/dev_77_25_D0_3E_E1_0D
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/service.c:change_state() 0x12bfea8: device 38:78:62:DB:91:2A profile gap-profile state changed: disconnected -> unavailable (0)
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/gap/gas.c:gap_remove() GAP profile remove (38:78:62:DB:91:2A)
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/service.c:btd_service_unref() 0x12bfea8: ref=0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:btd_device_unref() Freeing device /org/bluez/hci0/dev_77_25_D0_3E_E1_0D
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_service() Removing GATT service: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0001
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_characteristic() Removing GATT characteristic: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0001/char0002
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_service() Removing GATT service: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0028
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_characteristic() Removing GATT characteristic: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0028/char0029
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_descriptor() Removing GATT descriptor: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0028/char0029/desc002b
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_characteristic() Removing GATT characteristic: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0028/char002c
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_descriptor() Removing GATT descriptor: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0028/char002c/desc002e
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:notify_client_unref() owner :1.19
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:notify_client_free() owner :1.19
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_characteristic() Removing GATT characteristic: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0028/char002f
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_descriptor() Removing GATT descriptor: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0028/char002f/desc0031
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:notify_client_unref() owner :1.19
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:notify_client_free() owner :1.19
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_characteristic() Removing GATT characteristic: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0028/char0032
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/gatt-client.c:unregister_descriptor() Removing GATT descriptor: /org/bluez/hci0/dev_77_25_D0_3E_E1_0D/service0028/char0032/desc0034
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/device.c:device_free() 0x12bb190
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/audio/a2dp.c:a2dp_source_server_remove() path /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/audio/a2dp.c:a2dp_sink_server_remove() path /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/audio/avrcp.c:avrcp_target_server_remove() path /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10004
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/audio/avrcp.c:avrcp_controller_server_remove() path /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10003
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/network/manager.c:nap_server_remove() path /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/network/manager.c:gn_server_remove() path /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/network/manager.c:panu_server_remove() path /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/profiles/network/server.c:path_unregister() Unregistered interface org.bluez.NetworkServer1 on path /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10000
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10001
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_service_remove() /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:remove_uuid() sending remove uuid command for index 0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/sdpd-service.c:remove_record_from_server() Removing record with handle 0x10002
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:btd_adapter_unref() Freeing adapter /org/bluez/hci0
Nov 12 11:04:44 daemon.debug bluetoothd[954]: ../bluez-5.62/src/adapter.c:adapter_free() 0x12b0d00
Nov 12 11:04:44 daemon.info bluetoothd[954]: Exit
```
