### ISSUE TITLE
Segfault in neard agent

### ISSUE THREAD

**Issue by TobiasFella** [bluez/bluez#300]
On Fedora 35.

Steps to reproduce: 
- Install & start `neard`
- Enable polling (in this case through QtNfc, though that I don't think that matters)
- Try pairing Headphones using NFC
- bluetoothd crashes

Backtrace:
```
#0  _dbus_type_reader_recurse (reader=<optimized out>, sub=<optimized out>) at ../../dbus/dbus-marshal-recursive.c:1036
#1  0x000055acbd38a429 in process_message (msg=msg@entry=0x55acbf3acf40, remote=remote@entry=0x7fffd29cd1b0) at plugins/neard.c:584
#2  0x000055acbd38b94d in push_oob (conn=<optimized out>, data=<optimized out>, msg=0x55acbf3acf40) at plugins/neard.c:685
#3  push_oob (conn=<optimized out>, msg=0x55acbf3acf40, data=<optimized out>) at plugins/neard.c:651
#4  0x000055acbd4109e9 in process_message (connection=0x55acbf399ec0, message=0x55acbf3acf40, method=0x55acbd479168 <neard_methods+40>, iface_user_data=<optimized out>) at gdbus/object.c:246
#5  0x00007f4a9a1c34a9 in _dbus_object_tree_dispatch_and_unlock (found_object=<synthetic pointer>, message=<optimized out>, tree=0x55acbf397680) at ../../dbus/dbus-object-tree.c:1020
#6  dbus_connection_dispatch (connection=0x55acbf399ec0) at ../../dbus/dbus-connection.c:4745
#7  dbus_connection_dispatch (connection=connection@entry=0x55acbf399ec0) at ../../dbus/dbus-connection.c:4576
#8  0x000055acbd40b748 in message_dispatch (data=data@entry=0x55acbf399ec0) at gdbus/mainloop.c:59
#9  0x00007f4a9a24b39b in g_idle_dispatch (source=0x55acbf3974b0, callback=0x55acbd40b730 <message_dispatch>, user_data=0x55acbf399ec0) at ../glib/gmain.c:5897
#10 0x00007f4a9a24f05f in g_main_dispatch (context=0x55acbf395320) at ../glib/gmain.c:3381
#11 g_main_context_dispatch (context=0x55acbf395320) at ../glib/gmain.c:4099
#12 0x00007f4a9a2a42a8 in g_main_context_iterate.constprop.0 (context=0x55acbf395320, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4175
#13 0x00007f4a9a24e773 in g_main_loop_run (loop=0x55acbf396500) at ../glib/gmain.c:4373
#14 0x000055acbd380428 in mainloop_run () at src/shared/mainloop-glib.c:66
#15 mainloop_run_with_signal (func=0x55acbd3c1b70 <signal_callback>, user_data=0x0) at src/shared/mainloop-notify.c:188
#16 main (argc=<optimized out>, argv=<optimized out>) at src/main.c:1239
```

**Comment by TobiasFella** [comment]
Here's the relevant dbus call as recorded by dbus-monitor
```
method call time=1645635892.183535 sender=:1.442 -> destination=:1.426 serial=20 path=/org/bluez/neard_handover_agent; interface=org.neard.HandoverAgent; member=PushOOB
   array [
      dict entry(
         string "EIR"
         variant             array of bytes [
               2a 00 33 cc 40 56 db 94 0a 09 57 48 2d 58 42 39 30 30 4e 04 0d
               04 04 24 11 03 08 11 0b 11 0c 11 0d 11 0e 11 0f 11 1e 11 31 11
            ]
      )
      dict entry(
         string "State"
         variant             string "inactive"
      )
   ]
```
