### ISSUE TITLE
Crash immediately after connecting to a headset

### ISSUE THREAD

**Issue by kolayne** [bluez/bluez#544]
Degrade in 5.66 -> 5.67. When I try to connect to my headphones via `bluetoothctl`, they successfully connect and immediately disconnect: `bluetoothd` crashes.
```
[bluetooth]# connect E8:EE:CC:37:44:5A 
Attempting to connect to E8:EE:CC:37:44:5A
[CHG] Device E8:EE:CC:37:44:5A Connected: yes
[NEW] Endpoint /org/bluez/hci0/dev_E8_EE_CC_37_44_5A/sep1 
[NEW] Endpoint /org/bluez/hci0/dev_E8_EE_CC_37_44_5A/sep2 
[NEW] Transport /org/bluez/hci0/dev_E8_EE_CC_37_44_5A/sep1/fd0 
Connection successful
[DEL] Media /org/bluez/hci0 
	SupportedUUIDs: 0000110a-0000-1000-8000-00805f9b34fb
	SupportedUUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[DEL] Endpoint /org/bluez/hci0/dev_E8_EE_CC_37_44_5A/sep1 
[DEL] Endpoint /org/bluez/hci0/dev_E8_EE_CC_37_44_5A/sep2 
[DEL] Transport /org/bluez/hci0/dev_E8_EE_CC_37_44_5A/sep1/fd0 
Agent unregistered
[DEL] Controller 60:F2:62:13:98:E4 KoLin [default]
Waiting to connect to bluetoothd...
```

I tried to run `/usr/lib/bluetooth/bluetoothd` with `gdb`. Here's the backtrace at the moment of crash:
```
#0  a2dp_resume_complete (session=0x5555557046a0, err=0, user_data=0x555555704f90)
    at profiles/audio/transport.c:348
#1  0x000055555558043f in finalize_resume (data=0x5555556f77d0) at profiles/audio/a2dp.c:354
#2  0x0000555555586a3f in avdtp_start_resp (resp=0x555555704713, size=<optimized out>, 
    stream=0x5555556f7d90, session=0x5555557046a0) at profiles/audio/avdtp.c:2868
#3  avdtp_parse_resp (transaction=<optimized out>, size=<optimized out>, 
    buf=0x555555704713, signal_id=<optimized out>, stream=0x5555556f7d90, 
    session=0x5555557046a0) at profiles/audio/avdtp.c:2988
#4  session_cb (chan=<optimized out>, cond=<optimized out>, data=0x5555557046a0)
    at profiles/audio/avdtp.c:2286
#5  0x00007ffff7eab981 in g_main_dispatch (context=0x5555556b4840)
    at ../glib/glib/gmain.c:3460
#6  g_main_context_dispatch (context=0x5555556b4840) at ../glib/glib/gmain.c:4200
#7  0x00007ffff7f08b39 in g_main_context_iterate.isra.0 (context=0x5555556b4840, 
    block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/glib/gmain.c:4276
#8  0x00007ffff7eaaf3f in g_main_loop_run (loop=0x5555556b4a00) at ../glib/glib/gmain.c:4479
#9  0x0000555555576e32 in mainloop_run () at src/shared/mainloop-glib.c:66
#10 mainloop_run_with_signal (func=0x5555555c3d60 <signal_callback>, user_data=0x0)
    at src/shared/mainloop-notify.c:188
#11 main (argc=<optimized out>, argv=<optimized out>) at src/main.c:1450
```

Potentially relevant local variables:
```
(gdb) print *session
$7 = {ref = 3, version = 259, lseps = 0x5555556e8790, device = 0x5555556f3ec0, 
  state = AVDTP_SESSION_STATE_CONNECTED, io = 0x5555556b8a50, io_id = 164, 
  seps = 0x555555703140 = {0x555555706fc0, 0x5555557075b0}, streams = 0x5555557025d0 = {
    0x5555556f2370}, req_queue = 0x0, prio_queue = 0x0, pending_open = 0x0, 
  pending_open_io = 0x0, phy = 511, imtu = 672, omtu = 679, in = {active = 0, 
    no_of_packets = 1, transaction = 3 '\003', message_type = 2 '\002', signal_id = 7 '\a', 
    buf = "\004\b\b\b", '\000' <repeats 1019 times>, data_size = 0 '\000'}, 
  buf = 0x555555706ae0 "2\a\004$\001", discover = 0x0, req = 0x555555708180, dc_timer = 0, 
  dc_timeout = 1, stream_setup = 0}
(gdb) print *owner
$8 = {transport = 0x0, pending = 0x0, name = 0x555555702440 ":1.34", watch = 0}
(gdb) 
```

**Comment by Vudentz** [comment]
Duplicated of https://github.com/bluez/bluez/issues/542
