### ISSUE TITLE
segfault when connecting to earplug

### ISSUE THREAD

**Issue by domenkozar** [bluez/bluez#62]
Bluez 5.54

```(gdb) bt
#0  0x00007f07c459808a in raise () from /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libc.so.6
#1  0x00007f07c4582528 in abort () from /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libc.so.6
#2  0x00007f07c45d98a8 in __libc_message () from /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libc.so.6
#3  0x00007f07c45e0a0a in malloc_printerr () from /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libc.so.6
#4  0x00007f07c45e27f5 in _int_free () from /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libc.so.6
#5  0x0000561454342d61 in load_remote_seps ()
#6  0x0000561454345b28 in avdtp_set_state ()
#7  0x00005614543495d4 in avdtp_connect_cb ()
#8  0x000056145437d70b in connect_cb ()
#9  0x00007f07c48d631e in g_main_context_dispatch () from /nix/store/qv9g7c2z41lz22l1r7inp0i75xca3hqn-glib-2.64.5/lib/libglib-2.0.so.0
#10 0x00007f07c48d66d0 in g_main_context_iterate.isra () from /nix/store/qv9g7c2z41lz22l1r7inp0i75xca3hqn-glib-2.64.5/lib/libglib-2.0.so.0
#11 0x00007f07c48d69a3 in g_main_loop_run () from /nix/store/qv9g7c2z41lz22l1r7inp0i75xca3hqn-glib-2.64.5/lib/libglib-2.0.so.0
#12 0x00005614543dbf05 in mainloop_run ()
#13 0x00005614543dc35c in mainloop_run_with_signal ()
#14 0x0000561454338142 in main ()
```

log:
```
Dec 13 20:04:43 guava bluetoothd[772]: Endpoint registered: sender=:1.43 path=/MediaEndpoint/A2DPSink/SBC
Dec 13 20:05:08 guava bluetoothd[772]: Unable to load Endpoint: seid 1
Dec 13 20:05:08 guava bluetoothd[772]: free(): double free detected in tcache 2
Dec 13 20:05:08 guava systemd[1]: bluetooth.service: Main process exited, code=dumped, status=6/ABRT
Dec 13 20:05:08 guava systemd[1]: bluetooth.service: Failed with result 'core-dump'.
```

**Comment by domenkozar** [comment]
can't reproduce with 5.55
