### ISSUE TITLE
Local name is not included in the advertisement packet

### ISSUE THREAD

**Issue by giorgib** [bluez/bluez#727]
**Setup information**
- Host: Raspberry Pi 4
- OS: Debian GNU/Linux 11 (bullseye)
- Python version: 3.9.2
- Bluez version: 5.72 (also tested on 5.65 and the results were the same)

**Description**
I am utilizing the Bluez DBus API with the aim of including local name information in the advertisement packet. To validate this, I am using an NRF52840 sniffer. By default, the local name is only included in the scan response packet, but I assumed it could be added to the advertisement packet by specifying the 'local-name' in the 'Includes' property of the 'org.bluez.LEAdvertisement1' interface. This approach successfully worked for including tx-power in the advertisement packet.

However, setting ['local-name'] as the 'Includes' property for the 'org.bluez.LEAdvertisement1' interface results in a crash of the application. Is there any other way I could include the local name in the advertisement packet?

> Traceback (most recent call last):
  File "/home/pi/workspace/ble_minimal/main.py", line 157, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/workspace/ble_minimal/main.py", line 149, in main
    await advertising_manager.call_register_advertisement(advertisement.path, {})
  File "/home/pi/workspace/python_ble/.venv/lib/python3.9/site-packages/dbus_next/aio/proxy_object.py", line 92, in method_fn
    BaseProxyInterface._check_method_return(msg, intr_method.out_signature)
  File "/home/pi/workspace/python_ble/.venv/lib/python3.9/site-packages/dbus_next/proxy_object.py", line 62, in _check_method_return
    raise DBusError._from_message(msg)
dbus_next.errors.DBusError: Failed to parse advertisement.

You can find the minimal python code needed to reproduce the scenario at: https://gist.github.com/giorgib/be5c1d6af7c80b9613ab9fa23a43c6b5

**Advertisement packet when Includes=[]**

<img width="1728" alt="Screenshot 2024-01-18 at 00 11 35" src="https://github.com/bluez/bluez/assets/21182385/59de255f-0aef-42c0-93c2-0a0434c85729">

**Scan response packet when Includes=[]**

<img width="1728" alt="Screenshot 2024-01-18 at 00 12 22" src="https://github.com/bluez/bluez/assets/21182385/d8c08f05-478f-45b6-a3f5-efe1f8ed1d37">

**Advertisement packet when Includes=['tx-power']**

<img width="1728" alt="Screenshot 2024-01-18 at 00 13 10" src="https://github.com/bluez/bluez/assets/21182385/db788163-8d97-4296-9909-16c10fe72765">

**Scan response packet when Includes=['tx-power']**

<img width="1728" alt="Screenshot 2024-01-18 at 00 13 27" src="https://github.com/bluez/bluez/assets/21182385/88cf8908-c797-4d74-86c4-fc6c15038144">

**Comment by abqjln** [comment]
Workaround tested on multiple Raspberry Pi platforms:

  - `Raspberry Pi 5 Model B Rev 1.0`, `Debian 13.4 (trixie)`, `BlueZ 5.82`
  - `Raspberry Pi 4 Model B Rev 1.5`, `Debian 13.4 (trixie)`, `BlueZ 5.82`
  - `Raspberry Pi 3 Model B Plus Rev 1.3`, `Debian GNU/Linux 12 (bookworm)`, `BlueZ 5.66`

We hit the same practical limitation in the D-Bus `LEAdvertisement1` path: BlueZ’s internal “managed” advertising logic tended to push the local name into `SCAN_RSP`  instead of letting us place it reliably in primary `ADV_IND`. In our case, that made the D-Bus path unusable for a central that only cared about the primary advertisement name.

One related code path worth noting is `src/shared/ad.c`: the generic advertisement-data handling uses a `type_reject_list`, and the short/complete local-name AD types are treated as managed types rather than generic raw data. That appears to be part of what blocks forcing name AD structures through the D-Bus path. There are many other reject data type in `type_reject_list` that we did not test.

The working workaround was to bypass `LEAdvertisement1` for advertising payload registration and use a raw `MGMT` control socket with `MGMT_OP_ADD_ADVERTISING`  (`0x003E`) instead. We still kept `bluetoothd` alive for the rest of the stack, but used `MGMT` for explicit advertising payload control.

 The key implementation detail was to respect BlueZ/kernel `MGMT` ownership of the `Flags` AD structure:
  - do not also pack a raw `Flags` AD element into user `Adv_Data`
  - reserve the corresponding 3-byte reduction (`Length + Type + Value`) in the primary 31-byte advertising budget before placing the name

If we failed to do that, `ADD_ADVERTISING` returned `0x0D` (`rejected` / `invalid parameters`).

Also important: this required both `CAP_NET_ADMIN` and `CAP_NET_RAW`. Without those capabilities, `MGMT` writes either failed outright or ended in the same `0x0D` rejection path.

So the practical result was:
  - D-Bus `LEAdvertisement1`: not enough control over name placement in `ADV_IND`
  - raw `MGMT` `ADD_ADVERTISING`: worked, once `Flags` ownership/budget and Linux capabilities were handled correctly

I’m currently using this in a private project in C to bridge sensors to Garmin watches. Feel free to `@`-mention me here if you need more specifics on the `MGMT` packet structure.
