### ISSUE TITLE
Crash on device disconnect

### ISSUE THREAD

**Issue by serfreeman1337** [bluez/bluez#952]
```
$ /usr/lib/bluetooth/bluetoothd -v
5.78
```
bluetoothd crashes when keyboard goes to sleep and disconnects
```
Core was generated by `/usr/lib/bluetooth/bluetoothd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000062dd8bf08248 in notify_handler (data=0x62dbef20ef34, user_data=0x7ffeabbcdec0) at src/shared/uhid.c:94
94              if (notify->event != ev->type)
```

Backtrace:
```c++
#0  0x000062dd8bf08248 in notify_handler (data=0x62dbef20ef34, user_data=0x7ffeabbcdec0) at src/shared/uhid.c:94
#1  0x000062dd8bf03f0c in queue_foreach (queue=0x62ddc2fd48d0, function=0x62dd8bf08240 <notify_handler>, user_data=0x7ffeabbcdec0) at src/shared/queue.c:207
#2  0x000062dd8bf08e59 in uhid_read_handler (io=<optimized out>, user_data=0x62ddc2fd8d40) at src/shared/uhid.c:164
#3  0x000062dd8bf32f45 in watch_callback (channel=<optimized out>, cond=<optimized out>, user_data=<optimized out>) at src/shared/io-glib.c:157
#4  0x0000773c2e450299 in ?? () from /usr/lib/libglib-2.0.so.0
#5  0x0000773c2e4b2ec7 in ?? () from /usr/lib/libglib-2.0.so.0
#6  0x0000773c2e450fa7 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#7  0x000062dd8bf335c5 in mainloop_run () at src/shared/mainloop-glib.c:66
#8  0x000062dd8bf339f5 in mainloop_run_with_signal (func=func@entry=0x62dd8bea5c80 <signal_callback>, user_data=user_data@entry=0x0) at src/shared/mainloop-notify.c:189
#9  0x000062dd8be5865c in main (argc=<optimized out>, argv=<optimized out>) at src/main.c:1467
```

<details>
  <summary>valgrind</summary>

```c++
==7314== Memcheck, a memory error detector
==7314== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==7314== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==7314== Command: /usr/lib/bluetooth/bluetoothd -n
==7314== 
==7314== Syscall param socketcall.bind(my_addr.rc_bdaddr) points to uninitialised byte(s)
==7314==    at 0x4C6512B: bind (syscall-template.S:120)
==7314==    by 0x1EEF21: bt_log_open (log.c:118)
==7314==    by 0x1EEF21: bt_log_open (log.c:95)
==7314==    by 0x17CA54: __btd_log_init (log.c:172)
==7314==    by 0x12DB57: main (main.c:1401)
==7314==  Address 0x1fff000806 is on thread 1's stack
==7314==  in frame #1, created by bt_log_open (log.c:96)
==7314==  Uninitialised value was created by a stack allocation
==7314==    at 0x1EEEA0: bt_log_open (log.c:96)
==7314== 
==7314== Invalid read of size 8
==7314==    at 0x1D9EFF: queue_foreach (queue.c:206)
==7314==    by 0x1DEE58: uhid_read_handler (uhid.c:164)
==7314==    by 0x208F44: watch_callback (io-glib.c:157)
==7314==    by 0x48DD298: g_main_dispatch.lto_priv.0 (gmain.c:3344)
==7314==    by 0x493FEC6: UnknownInlinedFun (gmain.c:4152)
==7314==    by 0x493FEC6: g_main_context_iterate_unlocked.isra.0 (gmain.c:4217)
==7314==    by 0x48DDFA6: g_main_loop_run (gmain.c:4419)
==7314==    by 0x2095C4: mainloop_run (mainloop-glib.c:66)
==7314==    by 0x2099F4: mainloop_run_with_signal (mainloop-notify.c:189)
==7314==    by 0x12E65B: main (main.c:1467)
==7314==  Address 0x51286d8 is 8 bytes inside a block of size 16 free'd
==7314==    at 0x48478EF: free (vg_replace_malloc.c:989)
==7314==    by 0x1DA08D: queue_remove_if (queue.c:292)
==7314==    by 0x1DA12F: queue_remove_all (queue.c:321)
==7314==    by 0x1DE592: bt_uhid_unregister_all (uhid.c:300)
==7314==    by 0x15AF58: uhid_disconnect.part.0 (device.c:189)
==7314==    by 0x1D9F0B: queue_foreach (queue.c:207)
==7314==    by 0x1DEE58: uhid_read_handler (uhid.c:164)
==7314==    by 0x208F44: watch_callback (io-glib.c:157)
==7314==    by 0x48DD298: g_main_dispatch.lto_priv.0 (gmain.c:3344)
==7314==    by 0x493FEC6: UnknownInlinedFun (gmain.c:4152)
==7314==    by 0x493FEC6: g_main_context_iterate_unlocked.isra.0 (gmain.c:4217)
==7314==    by 0x48DDFA6: g_main_loop_run (gmain.c:4419)
==7314==    by 0x2095C4: mainloop_run (mainloop-glib.c:66)
==7314==  Block was alloc'd at
==7314==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==7314==    by 0x1DA25D: util_malloc (util.c:46)
==7314==    by 0x1D9CBA: queue_entry_new (queue.c:69)
==7314==    by 0x1D9CBA: queue_push_tail (queue.c:82)
==7314==    by 0x1DE4E3: bt_uhid_register (uhid.c:255)
==7314==    by 0x15B048: uhid_connadd (device.c:1004)
==7314==    by 0x15B048: uhid_connadd (device.c:985)
==7314==    by 0x15B0C4: encrypt_notify (device.c:1019)
==7314==    by 0x48DD298: g_main_dispatch.lto_priv.0 (gmain.c:3344)
==7314==    by 0x493FEC6: UnknownInlinedFun (gmain.c:4152)
==7314==    by 0x493FEC6: g_main_context_iterate_unlocked.isra.0 (gmain.c:4217)
==7314==    by 0x48DDFA6: g_main_loop_run (gmain.c:4419)
==7314==    by 0x2095C4: mainloop_run (mainloop-glib.c:66)
==7314==    by 0x2099F4: mainloop_run_with_signal (mainloop-notify.c:189)
==7314==    by 0x12E65B: main (main.c:1467)
==7314== 
==7314== Invalid read of size 8
==7314==    at 0x1D9F03: queue_foreach (queue.c:207)
==7314==    by 0x1DEE58: uhid_read_handler (uhid.c:164)
==7314==    by 0x208F44: watch_callback (io-glib.c:157)
==7314==    by 0x48DD298: g_main_dispatch.lto_priv.0 (gmain.c:3344)
==7314==    by 0x493FEC6: UnknownInlinedFun (gmain.c:4152)
==7314==    by 0x493FEC6: g_main_context_iterate_unlocked.isra.0 (gmain.c:4217)
==7314==    by 0x48DDFA6: g_main_loop_run (gmain.c:4419)
==7314==    by 0x2095C4: mainloop_run (mainloop-glib.c:66)
==7314==    by 0x2099F4: mainloop_run_with_signal (mainloop-notify.c:189)
==7314==    by 0x12E65B: main (main.c:1467)
==7314==  Address 0x51286d0 is 0 bytes inside a block of size 16 free'd
==7314==    at 0x48478EF: free (vg_replace_malloc.c:989)
==7314==    by 0x1DA08D: queue_remove_if (queue.c:292)
==7314==    by 0x1DA12F: queue_remove_all (queue.c:321)
==7314==    by 0x1DE592: bt_uhid_unregister_all (uhid.c:300)
==7314==    by 0x15AF58: uhid_disconnect.part.0 (device.c:189)
==7314==    by 0x1D9F0B: queue_foreach (queue.c:207)
==7314==    by 0x1DEE58: uhid_read_handler (uhid.c:164)
==7314==    by 0x208F44: watch_callback (io-glib.c:157)
==7314==    by 0x48DD298: g_main_dispatch.lto_priv.0 (gmain.c:3344)
==7314==    by 0x493FEC6: UnknownInlinedFun (gmain.c:4152)
==7314==    by 0x493FEC6: g_main_context_iterate_unlocked.isra.0 (gmain.c:4217)
==7314==    by 0x48DDFA6: g_main_loop_run (gmain.c:4419)
==7314==    by 0x2095C4: mainloop_run (mainloop-glib.c:66)
==7314==  Block was alloc'd at
==7314==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==7314==    by 0x1DA25D: util_malloc (util.c:46)
==7314==    by 0x1D9CBA: queue_entry_new (queue.c:69)
==7314==    by 0x1D9CBA: queue_push_tail (queue.c:82)
==7314==    by 0x1DE4E3: bt_uhid_register (uhid.c:255)
==7314==    by 0x15B048: uhid_connadd (device.c:1004)
==7314==    by 0x15B048: uhid_connadd (device.c:985)
==7314==    by 0x15B0C4: encrypt_notify (device.c:1019)
==7314==    by 0x48DD298: g_main_dispatch.lto_priv.0 (gmain.c:3344)
==7314==    by 0x493FEC6: UnknownInlinedFun (gmain.c:4152)
==7314==    by 0x493FEC6: g_main_context_iterate_unlocked.isra.0 (gmain.c:4217)
==7314==    by 0x48DDFA6: g_main_loop_run (gmain.c:4419)
==7314==    by 0x2095C4: mainloop_run (mainloop-glib.c:66)
==7314==    by 0x2099F4: mainloop_run_with_signal (mainloop-notify.c:189)
==7314==    by 0x12E65B: main (main.c:1467)
==7314== 
==7314== Invalid read of size 4
==7314==    at 0x1DE248: notify_handler (uhid.c:94)
==7314==    by 0x1D9F0B: queue_foreach (queue.c:207)
==7314==    by 0x1DEE58: uhid_read_handler (uhid.c:164)
==7314==    by 0x208F44: watch_callback (io-glib.c:157)
==7314==    by 0x48DD298: g_main_dispatch.lto_priv.0 (gmain.c:3344)
==7314==    by 0x493FEC6: UnknownInlinedFun (gmain.c:4152)
==7314==    by 0x493FEC6: g_main_context_iterate_unlocked.isra.0 (gmain.c:4217)
==7314==    by 0x48DDFA6: g_main_loop_run (gmain.c:4419)
==7314==    by 0x2095C4: mainloop_run (mainloop-glib.c:66)
==7314==    by 0x2099F4: mainloop_run_with_signal (mainloop-notify.c:189)
==7314==    by 0x12E65B: main (main.c:1467)
==7314==  Address 0x5128674 is 4 bytes inside a block of size 24 free'd
==7314==    at 0x48478EF: free (vg_replace_malloc.c:989)
==7314==    by 0x1DA11A: queue_remove_all (queue.c:326)
==7314==    by 0x1DE592: bt_uhid_unregister_all (uhid.c:300)
==7314==    by 0x15AF58: uhid_disconnect.part.0 (device.c:189)
==7314==    by 0x1D9F0B: queue_foreach (queue.c:207)
==7314==    by 0x1DEE58: uhid_read_handler (uhid.c:164)
==7314==    by 0x208F44: watch_callback (io-glib.c:157)
==7314==    by 0x48DD298: g_main_dispatch.lto_priv.0 (gmain.c:3344)
==7314==    by 0x493FEC6: UnknownInlinedFun (gmain.c:4152)
==7314==    by 0x493FEC6: g_main_context_iterate_unlocked.isra.0 (gmain.c:4217)
==7314==    by 0x48DDFA6: g_main_loop_run (gmain.c:4419)
==7314==    by 0x2095C4: mainloop_run (mainloop-glib.c:66)
==7314==    by 0x2099F4: mainloop_run_with_signal (mainloop-notify.c:189)
==7314==  Block was alloc'd at
==7314==    at 0x48447A8: malloc (vg_replace_malloc.c:446)
==7314==    by 0x1DA25D: util_malloc (util.c:46)
==7314==    by 0x1DE4A6: bt_uhid_register (uhid.c:249)
==7314==    by 0x15B048: uhid_connadd (device.c:1004)
==7314==    by 0x15B048: uhid_connadd (device.c:985)
==7314==    by 0x15B0C4: encrypt_notify (device.c:1019)
==7314==    by 0x48DD298: g_main_dispatch.lto_priv.0 (gmain.c:3344)
==7314==    by 0x493FEC6: UnknownInlinedFun (gmain.c:4152)
==7314==    by 0x493FEC6: g_main_context_iterate_unlocked.isra.0 (gmain.c:4217)
==7314==    by 0x48DDFA6: g_main_loop_run (gmain.c:4419)
==7314==    by 0x2095C4: mainloop_run (mainloop-glib.c:66)
==7314==    by 0x2099F4: mainloop_run_with_signal (mainloop-notify.c:189)
==7314==    by 0x12E65B: main (main.c:1467)
==7314== 
```
</details>

<details>
  <summary>Backtrace for archlinux package</summary>

```c++
#0  0x000056cc9c60b44c in notify_handler (data=0x56c9aac3c2f0, user_data=0x7fffcf163a00) at src/shared/uhid.c:89
#1  queue_foreach (queue=0x56ccc6104140, function=0x56cc9c6028e0 <notify_handler>, user_data=0x7fffcf163a00) at src/shared/queue.c:207
#2  queue_foreach (queue=0x56ccc6104140, function=0x56cc9c6028e0 <notify_handler>, user_data=0x7fffcf163a00) at src/shared/queue.c:190
#3  uhid_read_handler (io=<optimized out>, user_data=<optimized out>) at src/shared/uhid.c:164
#4  0x000056cc9c62cbf9 in watch_callback (channel=<optimized out>, cond=<optimized out>, user_data=<optimized out>) at src/shared/io-glib.c:157
#5  0x000078fbde158299 in g_main_dispatch (context=0x56ccc60ea800) at ../glib/glib/gmain.c:3344
#6  0x000078fbde1baec7 in g_main_context_dispatch_unlocked (context=0x56ccc60ea800) at ../glib/glib/gmain.c:4152
#7  g_main_context_iterate_unlocked.isra.0 (context=0x56ccc60ea800, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4217
#8  0x000078fbde158fa7 in g_main_loop_run (loop=0x56ccc60ea9f0) at ../glib/glib/gmain.c:4419
#9  0x000056cc9c55b005 in mainloop_run () at src/shared/mainloop-glib.c:66
#10 mainloop_run_with_signal (func=0x56cc9c5b3280 <signal_callback>, user_data=0x0) at src/shared/mainloop-notify.c:189
#11 main (argc=<optimized out>, argv=<optimized out>) at src/main.c:1467
```
</details>

**Comment by ninja-** [comment]
I was about to report this as well. I have this crash every time my bluetooth keyboard wakes up my laptop from s2idle

**Comment by Vudentz** [comment]
Looks like this is a list removal while iterating on it kind of problem, will attempt to fix it asap.

**Comment by Vudentz** [comment]
@serfreeman1337 @ninja- could one of you guys test with the above changes?

**Comment by serfreeman1337** [comment]
Can confirm that there are no more crashes
