### ISSUE TITLE
The test/map-client script fails to run because it still uses Python2 types.

### ISSUE THREAD

**Issue by tholin** [bluez/bluez#971]
The test script `test/map-client` still uses the Python2 only types `unicode` and `long` at line 38. Trying to run the script as `./map-client --device=AA:BB:CC:DD:EE:FF --chdir=telecom/msg --lsmsg=inbox` fails with a NameError as a result. If I remove the Python2 types it runs and displays my messages from a Pixel 8a phone.

    Traceback (most recent call last):
      File "/var/tmp/portage/net-wireless/bluez-5.77/work/bluez-5.77/test/./map-client", line 207, in <module>
        map_client.list_messages(options.ls_msg)
      File "/var/tmp/portage/net-wireless/bluez-5.77/work/bluez-5.77/test/./map-client", line 143, in list_messages
        print(pformat(unwrap(ret)))
                      ^^^^^^^^^^^
      File "/var/tmp/portage/net-wireless/bluez-5.77/work/bluez-5.77/test/./map-client", line 36, in unwrap
        return dict([(unwrap(k), unwrap(v)) for k, v in x.items()])
                      ^^^^^^^^^
      File "/var/tmp/portage/net-wireless/bluez-5.77/work/bluez-5.77/test/./map-client", line 38, in unwrap
        for t in [unicode, str, long, int, float, bool]:
                  ^^^^^^^
    NameError: name 'unicode' is not defined

**Comment by gudnimg** [comment]
To add to this, `long` type is also not relevant anymore on Python 3.

**Comment by tholin** [comment]
Still an issue.
